world_name: "empty"
drones:
  - model_type: "crazyflie"
    model_name: "drone0"
    xyz:
      - 0.0
      - 0.0
      - 0.3
  - model_type: "crazyflie"
    model_name: "drone1"
    xyz:
      - -0.5
      - 0.0
      - 0.3
  - model_type: "crazyflie"
    model_name: "drone2"
    xyz:
      - -1.0
      - 0.0
      - 0.3