/**:
  ros__parameters:
    use_sim_time: True
  platform:
    ros__parameters:
      cmd_freq: 30.0  # Hz of platform commands send
      info_freq: 10.0  # Hz of platform info publish
      enable_takeoff_platform: false  # Enable takeoff platform, only for debugging purposes
      enable_land_platform: false  # Enable land platform, only for debugging purposes
  state_estimator:
    ros__parameters:
      plugin_name: ground_truth
      use_gazebo_tf: True
  controller_manager:
    ros__parameters:
      plugin_name: pid_speed_controller
      cmd_freq: 30.0  # Hz of platform commands send
      info_freq: 10.0  # Hz of platform info publish
      odom_frame_id: "odom"
      base_frame_id: "base_link"
      use_bypass: true
      tf_timeout_threshold: 0.05  # seconds
      proportional_limitation: true
      position_control:
        reset_integral: false
        antiwindup_cte: 0.5
        alpha: 0.2
        kp:
          x: 1.0
          y: 1.0
          z: 1.0
        kd:
          x: 0.0
          y: 0.0
          z: 0.0
        ki:
          x: 0.01
          y: 0.01
          z: 0.01
      yaw_control:
        reset_integral: false
        antiwindup_cte : 1.0
        alpha: 0.3
        kp: 1.0
        kd: 0.001
        ki: 0.0
  TakeoffBehavior:
    ros__parameters:
      takeoff_plugin_name: takeoff_plugin_position
  LandBehavior:
    ros__parameters:
      land_plugin_name: land_plugin_speed
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: go_to_plugin_position
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: follow_path_plugin_position