/**:
  # Global Parameters
  ros__parameters:
    use_sim_time: False

/**:
  # Basic Robotics Functions
  platform:
    ros__parameters:
      cmd_freq: 30.0  # Hz of platform commands send

  # State Estimator
  state_estimator:
    ros__parameters:
      plugin_name: "raw_odometry"

  # Motion Controller
  controller_manager:
    ros__parameters:
      cmd_freq: 30.0 # Hz of controller commands send
      plugin_name: "pid_speed_controller"
      # Plugin parameters
      proportional_limitation: true
      position_control:
        antiwindup_cte: 1.0
        alpha: 0.3
        kp:
          x: 0.4
          y: 0.4
          z: 0.4
        kd:
          x: 0.0
          y: 0.0
          z: 0.0
        ki:
          x: 0.0001
          y: 0.0001
          z: 0.0001

  # Behaviors
  TakeoffBehavior:
    ros__parameters:
      takeoff_plugin_name: takeoff_plugin_position
  LandBehavior:
    ros__parameters:
      land_plugin_name: land_plugin_speed
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: go_to_plugin_position
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: follow_path_plugin_position

# Specific Parameters for each drone
drone0:
  platform:
    ros__parameters:
      uri: radio://0/80/2M/E7E7E7E709
